### ISSUE TITLE
Non_Unicast capture filter should use `>= 224.0.0.0` ?

### ISSUE THREAD

**Issue by shusugmt** [euro-ix/IXP-Watch#2]
https://github.com/euro-ix/IXP-Watch/blob/master/bin/ixp-watch#L355

I believe 223.x.x.x is still unicast address. The current filter `-Y "ip.dst >= 223.0.0.0 and not gre and not l2tp"` will capture any packets with dst IP address set to 223.0.0.0/8 as Non_Unicast, which is incorrect.

**Comment by listerr** [comment]
Thanks. I've fixed this in the new release. Not sure why it was like that...
