### ISSUE TITLE
bash string compare errors

### ISSUE THREAD

**Issue by lucix-mich** [euro-ix/IXP-Watch#3]
Hello,

I came accross errors while running IXP Watch. I found a solution, but I'm not entirely sure I completely understand the issue - because I don't think I would be the first one noticing.

**Problem:**

Any string compare operation using "==" as operator would throw an error. Example code:
```
...
if [ "$MY_IP" == "" ] ; then
# Newer Linux - subtle change to ifconfig:
...

```

**Error message:**

`/usr/local/bin/ixp-watch: 152: [: unexpected operator
`
(the line number is offset; I edited the script)

**Solution:**

I had to use the single equal operator "=" instead of double equal "==" to fix my errors. According to bash manpage:

`= should be used with the test command for POSIX conformance. 
`

This is on plain vanilla Debian 10 aka buster.

**Comment by rfc1036** [comment]
You are correct: == is a bashism and should be replaced with =.  Debian does not use bash as /bin/sh.

**Comment by listerr** [comment]
Hmm. I don't seem to have the same problem, and we have exactly the same environment (Debian buster)  

The script has always used `#!/bin/bash` at the top to explicitly use it and not rely on the default shell being bash.

It's also possible it's an unclosed quote somewhere else in the script; this has caught me out a few times.

**Comment by lucix-mich** [comment]
Rob, exactly why I'm all but sure about this. I don't see why in my case the ixp-watch script should be executed in bash's POSIX mode.

**Comment by lucix-mich** [comment]
My ixpwatch user has /bin/sh as shell. But I would nevertheless expect the cron execution environment to honour the #! in the ixp-watch script.

**Comment by listerr** [comment]
I've just done a fresh install from the version currently on github, and seems to be okay.

Wonder if something has changed and need to look into making it more robust string checking?

Here's my version of bash:

```
root@ixpwatch:~# /bin/bash --version
/bin/bash --version
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
root@ixpwatch:~# ls -la /bin/bash
ls -la /bin/bash
-rwxr-xr-x 1 root root 1168776 Apr 18  2019 /bin/bash
root@ixpwatch:~#

root@ixpwatch:~# ls -la /usr/bin/bash
ls -la /usr/bin/bash
-rwxr-xr-x 1 root root 1168776 Apr 18  2019 /usr/bin/bash
root@ixpwatch:~#

```

```
root@ixpwatch:~# uname -an
uname -an
Linux ixpwatch.lonap.net 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
```

```
root@ixpwatch:~# cat /etc/debian_version
cat /etc/debian_version
10.10
```

**Comment by lucix-mich** [comment]
My environment matches yours. But I got my errors only when manually runing the cron job file using su. This seems confirmed by more tests: only in this case, i.e. executing under su to switch user, do I get errors, only in this case I seem to be in a POSIX environment but I can't explain why.

Concerning double equal, I would say '=' is more robust - works in plain bash and also in POSIX shells.

**Comment by listerr** [comment]
I've just pushed an update which should hopefully fix this. I've removed all the `"=="` and `""` tests and replaced with -z or -n,.
