### ISSUE TITLE
conffile: suggest moving another parameter

### ISSUE THREAD

**Issue by lucix-mich** [euro-ix/IXP-Watch#4]
Dear IXP Watch team,

Thanks for splitting config into a separate file - makes updates definitely easier!

However I suggest also moving COUNTSFILE into the config file, since by default it's built with the $NETWORK name - which can easily contain characters undesireable in a filename (as the comment itself says).

Maybe even switch to a configuration mode that allows overrides in the conf file, otherwise falling back to defaults, something like this:

[ -z "$CONF-PARAMETER" ] && CONF-PARAMETER="some sane default value"

This could for example be worthwhile for the paths of the various binaries, which will fit most of the time.

Thanks and cheers

Michel

**Comment by listerr** [comment]
Thanks Michel,

I'll fix this in the next update.

Rob
